# Project information
site_name: zyong
site_description: notes blog proj
site_author: zhang yong
site_url: https://zyongzhangyong.github.io/

# Repository
repo_name: zyongzhangyong.github.io
repo_url: https://github.com/zyongzhangyong/zyongzhangyong.github.io
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 zhangyong'

nav:
- Home: index.md
- Notes:
    - gcc: notes/gcc.md
    - python: notes/python.md
    - pip: notes/pip.md
    - git: notes/git.md
    - npm: notes/npm.md
    - http-server: notes/http-server.md
    - mkdocs: notes/mkdocs.md
    - markdown: notes/markdown.md
- Awesome:
    - soft: awsome/aw_soft.md
- MyProj:
    - mlog: myproj/mlog.md
    - bmp: myproj/bmp.md
    - cauto: myproj/cauto.md
- Books:
    - Resource: book/book_src.md
    - 读书笔记: book/book_notes.md
theme:
  name: material
  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  feature:
    tabs: true
  palette:
    primary: black
    accent: black
  font:
    text: Roboto
    code: Roboto Mono
#  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"
    

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde